### ISSUE TITLE
RL Agent

### ISSUE THREAD

**Issue by kiritowu** [kiritowu/pong-ai#3]
Develop a simple RL Agent that takes in the game environment (raw pixel) and makes a discrete decision (up or down) to maximise the score. The RL agent needs to run in real-time and play against the human player.

## To-Do
- [x] ~~Train an RL agent (*maybe [ElegantRL](https://github.com/AI4Finance-Foundation/ElegantRL)*) OR find pretrained weight on open source website~~ (Retrain RL Agent with native pygame env + simplified observation space)
- [x] Expose AI decisions to the real-time game engine.
- [x] Expose pong environment to the agent
