### ISSUE TITLE
Pong Leaderboard

### ISSUE THREAD

**Issue by Tien-Cheng** [kiritowu/pong-ai#5]
To build a simple score leaderboard that shows real-time live scores along with the username.

## To-Do
- [x] Design UI and simple webpage
- [x] Create Firebase Project for hosting of website, Firestore database
- ~~[ ] Expose firebase function backend code if necessary~~ (Can be handled using native firestore event)
- [x] Deploy the project: https://pong-ai-podium.web.app/

**Comment by kiritowu** [comment]
Kudos to @aqilakmal  and @notsql for the wonderful UI and design!
![image](https://user-images.githubusercontent.com/70313929/162466823-d567a665-dfa5-424e-8561-513c660237ed.png)
